// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztlmftmpobqfyauayxkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bG1mdG1wb2JxZnlhdWF5eGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDczMDEsImV4cCI6MjA3MDA4MzMwMX0.MZ0irP-UkC13UU70hW1u46o56nvOkyVZoutdpWzkAHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});